version: "3"

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5438:5432"
    volumes:
      - postgres13:/var/lib/postgresql/data

  redis:
    image: redis:7.0.15-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/cart_development
      - REDIS_URL=redis://redis:6379/0

  test:
    build: .
    command: bash -c "bundle install && bin/rails db:create db:schema:load && bin/rails spec"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/cart_test
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails

  worker:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/store_development
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres13:
  redis_data:

